# Generated by Django 3.2 on 2021-07-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='anrede',
            field=models.CharField(choices=[('Herr', 'Herr'), ('Frau', 'Frau')], max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='anrede',
            field=models.CharField(choices=[('Herr', 'Herr'), ('Frau', 'Frau')], max_length=200),
        ),
    ]
